add network-utilities script to coda-network-services and refactors
MinaProtocol/coda-automation pull request #508
Opened 2020-12-07 20:14 UTC by 0x0I

Extend *coda-network-services* with `network-utilities` script to be used for network operations like cleanup and infra monitoring/reporting. Also refactor its services DIR and Dockerfile to be self contained within project root.

2020-12-07 21:30 UTC, 0x0I commented on services/coda-network-services/scripts/network-utilities.py
> +                        command = "kubectl delete all --all -n {namespace}".format(namespace=ns)
todo: delete using api (...?)

2020-12-08 00:02 UTC, es92 requested changes

2020-12-08 00:02 UTC, es92 commented on services/coda-network-services/scripts/network-utilities.py
> +                        command = "kubectl delete all --all -n {namespace}".format(namespace=ns)
What's to prevent this from deleting a running network? The 7 days above for example doesn't seem compatible with our current 3 week old network

2020-12-08 00:26 UTC, 0x0I commented on services/coda-network-services/Makefile
> +	docker build -t codaprotocol/coda-network-services:$(version) -f Dockerfile  .
Agreed on one script though seems like it could either be symlinked here or there (whichever works). Are there other scripts using it btw (thinking was that there aren't and it could be moved here)?

2020-12-08 00:27 UTC, 0x0I commented on services/coda-network-services/Makefile
> +	docker build -t codaprotocol/coda-network-services:$(version) -f Dockerfile  .
Just seems a bit awkward and I'm thinking not a good practice to have to `cd` into another DIR specifically in order to build.

2020-12-08 00:31 UTC, es92 commented on services/coda-network-services/Makefile
> +	docker build -t codaprotocol/coda-network-services:$(version) -f Dockerfile  .
That makes sense, and the symlink solution is a good one! I use that script sometimes manually so would prefer if the main stays in /scripts, but yeah +1 on symlinking a version inside coda-network-services

2020-12-08 00:32 UTC, 0x0I commented on services/coda-network-services/scripts/network-utilities.py
> +                        command = "kubectl delete all --all -n {namespace}".format(namespace=ns)
Currently only set to execute against integration testnets on the dedicated integration test k8s cluster. Shouldn't affect QA nets, dev nets or other testnets.

2020-12-08 00:35 UTC, 0x0I commented on services/coda-network-services/scripts/network-utilities.py
> +                        command = "kubectl delete all --all -n {namespace}".format(namespace=ns)
Also the 7 day setting is arbitrary and default. It's meant to be overridden based on the use-case. For integration tests, 7 days seems pretty reasonable though whatever makes more sense here works for me.

2020-12-08 00:44 UTC, es92 commented on services/coda-network-services/scripts/network-utilities.py
> +                        command = "kubectl delete all --all -n {namespace}".format(namespace=ns)
Ah I missed that its conditional. Makes sense as long as its not the default for testnet / qa nets

2020-12-08 12:44 UTC, 0x0I commented on services/coda-network-services/scripts/network-utilities.py
> +                        command = "kubectl delete all --all -n {namespace}".format(namespace=ns)
Got it and updated both the default patterns and contexts to empty lists to force a no-op by default without custom/explicit configuration.

2020-12-08 22:39 UTC, lk86 commented on services/coda-network-services/Dockerfile
> +FROM python:3.7-stretch
Maybe switch it to stretch-slim and install python3.7 alongside the other dependencies? I like to keep everything on slim images so that debian automatically handles cleaning the apt-cache, man pages, and other random files that containers don't need.

2020-12-08 22:40 UTC, lk86 approved these changes
Looks great! much cleaner and more self-contained.

2020-12-08 23:25 UTC, 0x0I commented on services/coda-network-services/Dockerfile
> +FROM python:3.7-stretch
Sure - there's also a [python:3.7.x-slim-buster](https://hub.docker.com/layers/python/library/python/3.7.9-slim-buster/images/sha256-05d4caed5b6ced951dc43c4f46f13daca790d4d2081eae5824a1459226d651e7?context=explore).

Supporting the python image base myself due to proper/convenient path and environment setup for executing python scripts. I get the goal is to support scripts of any lang tho we're currently only using bash & python so seems to be worth setting up for at least python w/ bash setup by default for the most part.

2020-12-08 23:39 UTC, lk86 commented on services/coda-network-services/Dockerfile
> +FROM python:3.7-stretch
python:3.7.x-slim-buster totally works for me 👍 if the scripts and whatnot work on buster its preferable to stretch for sure, and a pre-made python slim image is perfect.

2020-12-09 00:41 UTC, 0x0I commented on services/coda-network-services/scripts/random_restart.py
> +#!/usr/bin/env python3
currently set as a hard-link (vs. symbolic-link) due to docker mount issue w/ symbolic links

2020-12-10 15:00 UTC, merged